import unittest
from app.services.email_service import parse_news_content

class TestParsing(unittest.TestCase):

    def test_parse_news_content(self):
        raw_content = """
--- 
📰 India tests Integrated Air Defence Weapon System, shoots 3 targets simultaneously 🚀🇮🇳 
🤖 theaipoint: DRDO’s eye is sharp! Air Defence ka triple dhamaka—desh ki suraksha ab next level pe! Kya aap taiyar ho? 🚀🔥 
🖼️ Stock Images: 1. https://unsplash.com/photos/Y8riNmDqkCg (missile defense system) 2. https://unsplash.com/photos/k_T9fQP2_d8 (Indian Air Force jets) 
#️⃣ Hashtags: - Instagram: #indiandefense #drdo #airdefense #technologynews #indiatoday #defencetechnology #indiasecures - X/Twitter: #DRDO #IndiaDefence #AirDefenceTest - Facebook: #IndiaStrikesBack #DefenceTech 
📌 Source: Generated by AI (LLM model) 
---
"""
        news_items = parse_news_content(raw_content)
        self.assertEqual(len(news_items), 1)
        item = news_items[0]
        self.assertEqual(item['title'], "India tests Integrated Air Defence Weapon System, shoots 3 targets simultaneously 🚀🇮🇳")
        self.assertIn("DRDO’s eye is sharp!", item['comment'])
        self.assertEqual(len(item['images']), 2)
        self.assertEqual(item['images'][0], "https://unsplash.com/photos/Y8riNmDqkCg")
        self.assertIn("#indiandefense", item['hashtags'])
        self.assertEqual(item['source'], "Generated by AI (LLM model)")

if __name__ == '__main__':
    unittest.main()
